# Generated by Django 4.1.2 on 2022-11-01 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url_name", models.CharField(max_length=255)),
                ("profile_image", models.ImageField(upload_to="")),
                ("background_image", models.ImageField(upload_to="")),
                ("full_name", models.CharField(max_length=255)),
                ("evaluation_date", models.DateField(auto_now_add=True)),
                ("connections", models.IntegerField()),
                ("about", models.TextField()),
                ("head_title", models.CharField(max_length=255)),
                ("education", models.JSONField()),
                ("contact_info", models.JSONField()),
                ("skills", models.JSONField()),
                ("recommendations", models.JSONField()),
                ("experience", models.JSONField()),
                ("certifications", models.JSONField()),
                ("languages", models.JSONField()),
                ("projects", models.JSONField()),
                ("authoral_posts", models.IntegerField()),
            ],
        ),
    ]
